Part 10
TimLit13/TestGuru pull request #14
Opened 2022-02-12 10:28 UTC by TimLit13

Add sessions

2022-02-12 18:14 UTC, BubuntuClu requested changes

2022-02-12 18:14 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +      cookies[:user_url] = request.path
что за `user_url`? имя ключа не говорит о своей надобности. хранит в себе какой-то юрл пользователя. ссылка на его профиль? не понятно

2022-02-12 18:14 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:user_url]
`redirect_to cookies[:user_url] || root_path` навсякий случай

2022-02-12 18:14 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +  before_action :authenticate_user!
что на счет того чтобы поместить этот метод в ApplicationController и не вызывать в каждом дочернем?

2022-02-12 18:14 UTC, BubuntuClu commented on app/models/user.rb
> +  EMAIL_FORMAT = /\A[a-zA-Z0-9.!\#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*\z/
используй регулярку из модуля `URI`

2022-02-12 18:14 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :first_name, presence: true
`validates :first_name, : last_name, presence: true`

2022-02-12 18:14 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, presence: true
` validates :email, presence: true, format: { with: EMAIL_FORMAT, message: "не является email"}, uniqueness: true`

2022-02-12 18:14 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :first_name, presence: true
а, так и было. почему разделил?

2022-02-12 18:14 UTC, BubuntuClu commented on config/routes.rb
> +  get 'users/new'
дублирует путь на 5ой строке

2022-02-12 18:14 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, presence: true
в БД надо еще уникальный индекс добавить

2022-02-13 07:28 UTC, TimLit13 commented on app/controllers/application_controller.rb
> +      cookies[:user_url] = request.path
исправил

2022-02-13 07:28 UTC, TimLit13 commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:user_url]
исправил

2022-02-13 07:28 UTC, TimLit13 commented on app/controllers/test_passages_controller.rb
> +  before_action :authenticate_user!
исправил

2022-02-13 07:28 UTC, TimLit13 commented on app/models/user.rb
> +  EMAIL_FORMAT = /\A[a-zA-Z0-9.!\#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*\z/
исправил

2022-02-13 07:28 UTC, TimLit13 commented on app/models/user.rb
> +  validates :first_name, presence: true
Чтобы удобнее читать было.
Вернул назад.

2022-02-13 07:28 UTC, TimLit13 commented on app/models/user.rb
> +  validates :email, presence: true
добавил

2022-02-13 07:29 UTC, TimLit13 commented on config/routes.rb
> +  get 'users/new'
исправил

2022-02-13 09:40 UTC, merged