Part 18 badges
TimLit13/TestGuru pull request #24
Opened 2022-04-02 15:10 UTC by TimLit13

Add badges and achievements feature

2022-04-02 16:06 UTC, BubuntuClu requested changes

2022-04-02 16:06 UTC, BubuntuClu commented on app/controllers/achievements_controller.rb
> +    @achievements = Achievement.where(user_id: current_user.id).order(created_at: :desc)
почему не через ассоциацию получаешь ачивки? `current_user.achiements`?

2022-04-02 16:06 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    if TestPassage.exists?(params[:id])
зачем тут проверка на существование? вроде бы делали же метод для обработки пустого объекта в вопросах, тут можно продублировать

2022-04-02 16:06 UTC, BubuntuClu commented on app/models/badge.rb
> +  has_many :achievements, dependent: :destroy
а зачем отдельная таблица для ачивок? почему сама таблица баджей не подходит?

2022-04-02 16:06 UTC, BubuntuClu commented on app/services/achievement_service.rb
> +    if success_test_first_try?
ты же хотел в таблице хранить имя метода и вызывать из модели метод. так и надос делать

у тебя будет 50 баджей и 50 правил, тут будет 50  `if` выражений? это плохо. надо переделать, чтобы не надо было править метод вызова правил

2022-04-02 16:06 UTC, BubuntuClu commented on app/services/achievement_service.rb
> +  def reward_achievement
назови метод `call`

2022-04-02 16:06 UTC, BubuntuClu commented on app/services/achievement_service.rb
> +    @test_passage.test_passage_success? && (@user.test_passages.count{ |test_passage| test_passage.test_id ==  @test.id } <= 1)
рубишные обработки надо заменить на запрос к БД. зачем тебе в руби считать количество тестов? отфильтруй в БД

2022-04-02 16:06 UTC, BubuntuClu commented on app/services/achievement_service.rb
> +    test_ids = Category.find(@test.category_id).tests.pluck(:id)
сюда параметром будет приходить имя категории, надо будет искать тесты по названию категории. подобный метод у тебя есть в тестах

2022-04-02 16:06 UTC, BubuntuClu commented on app/services/achievement_service.rb
> +  def success_level_complete?
и сюда параметром будет приходить - уровень тестов

2022-04-02 16:06 UTC, BubuntuClu commented on app/services/achievement_service.rb
> +         .select{ |test_passage| test_passage.completed? && test_passage.test_passage_success? }
надо заменить на фильтрацию через БД

2022-04-02 16:06 UTC, BubuntuClu commented on db/migrate/20220327162911_create_achievements.rb
> +    create_table :achievements do |t|
мне кажется, лучше назвать `user_badges` чтобы название таблицы не смущала

2022-04-06 20:29 UTC, TimLit13 commented on app/controllers/achievements_controller.rb
> +    @achievements = Achievement.where(user_id: current_user.id).order(created_at: :desc)
откорректировал

2022-04-06 20:29 UTC, TimLit13 commented on app/controllers/test_passages_controller.rb
> +    if TestPassage.exists?(params[:id])
откорректировал

2022-04-06 20:29 UTC, TimLit13 commented on app/models/badge.rb
> +  has_many :achievements, dependent: :destroy
откорректировал

2022-04-06 20:29 UTC, TimLit13 commented on app/services/achievement_service.rb
> +    if success_test_first_try?
откорректировал

2022-04-06 20:30 UTC, TimLit13 commented on app/services/achievement_service.rb
> +  def reward_achievement
откорректировал

2022-04-06 20:30 UTC, TimLit13 commented on app/services/achievement_service.rb
> +    @test_passage.test_passage_success? && (@user.test_passages.count{ |test_passage| test_passage.test_id ==  @test.id } <= 1)
откорректировал

2022-04-06 20:30 UTC, TimLit13 commented on app/services/achievement_service.rb
> +    test_ids = Category.find(@test.category_id).tests.pluck(:id)
откорректировал

2022-04-06 20:30 UTC, TimLit13 commented on app/services/achievement_service.rb
> +  def success_level_complete?
откорректировал

2022-04-06 20:30 UTC, TimLit13 commented on app/services/achievement_service.rb
> +         .select{ |test_passage| test_passage.completed? && test_passage.test_passage_success? }
откорректировал

2022-04-06 20:30 UTC, TimLit13 commented on db/migrate/20220327162911_create_achievements.rb
> +    create_table :achievements do |t|
откорректировал

2022-04-07 06:29 UTC, BubuntuClu commented on app/services/achievement_service.rb
> +    test_ids = Category.find(category_level).tests.pluck(:id)
используй метод из модели теста, чтобы найти тесты по названию категории. сейчас у тебя тут происходит 2 запроса в БД, а в том методе будет один запрос

2022-04-10 07:09 UTC, TimLit13 commented on app/services/achievement_service.rb
> +    test_ids = Category.find(category_level).tests.pluck(:id)
откорректировал

2022-04-10 07:09 UTC, merged